# Generated by Django 4.2.3 on 2023-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=77)),
                ('order_id', models.PositiveIntegerField()),
                ('refund_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('request_date', models.DateField()),
                ('processed_date', models.DateField()),
            ],
        ),
    ]
