# Generated by Django 4.2.3 on 2023-07-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=90)),
                ('shipDate', models.DateField()),
                ('shipping_method', models.CharField(max_length=90)),
            ],
        ),
    ]
